/*
 * Zidar - Build system scripts.
 * Copyright (c) 2025-2026 Milos Tosic, Rudji Games. All rights reserved.
 * License: https://github.com/RudjiGames/zidar/blob/master/LICENSE
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void help()
{
	printf(
		"Usage: bin2c -s <src> -d <dst> -v <var>\n"
		"\n"
		" args:\n"
		"  src:   Source binary file\n"
		"  dst:   Destination C/H file\n"
		"  var:   Variable name (optional)\n"
		"\n"
		"Options:\n"
		"  -h, -?, -help     Displays this help and exits.\n"
	);
	exit(0);
}

void error(const char* _message)
{
	printf("Error: %s\n", _message);
	exit(1);
}

/* Sanitize a filename into a valid C identifier */
void make_identifier(const char* _filename, char* _out, size_t _outSize)
{
	const char* base = _filename;
	const char* p;

	/* find last path separator */
	for (p = _filename; *p; ++p)
	{
		if (*p == '/' || *p == '\\')
			base = p + 1;
	}

	size_t i = 0;
	for (p = base; *p && i < _outSize - 1; ++p)
	{
		char c = *p;
		if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9'))
			_out[i++] = c;
		else
			_out[i++] = '_';
	}

	/* ensure it doesn't start with a digit */
	if (i > 0 && _out[0] >= '0' && _out[0] <= '9')
		_out[0] = '_';

	_out[i] = '\0';
}

int main(int argc, char** argv)
{
	const char* src = NULL;
	const char* dst = NULL;
	const char* var = NULL;
	int i;

	if (argc < 2)
		help();

	for (i = 1; i < argc; ++i)
	{
		if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "-?") == 0 || strcmp(argv[i], "-help") == 0)
			help();
		else if (strcmp(argv[i], "-s") == 0 && i + 1 < argc)
			src = argv[++i];
		else if (strcmp(argv[i], "-d") == 0 && i + 1 < argc)
			dst = argv[++i];
		else if (strcmp(argv[i], "-v") == 0 && i + 1 < argc)
			var = argv[++i];
	}

	if (!src)
		error("Source file not specified (-s)");
	if (!dst)
		error("Destination file not specified (-d)");

	/* Read source binary file */
	FILE* fin = fopen(src, "rb");
	if (!fin)
		error("Could not open source file");

	fseek(fin, 0, SEEK_END);
	long size = ftell(fin);
	fseek(fin, 0, SEEK_SET);

	unsigned char* data = (unsigned char*)malloc(size);
	if (!data)
	{
		fclose(fin);
		error("Out of memory");
	}

	if ((long)fread(data, 1, size, fin) != size)
	{
		free(data);
		fclose(fin);
		error("Failed to read source file");
	}
	fclose(fin);

	/* Determine variable name */
	char varBuf[256];
	if (!var)
	{
		make_identifier(src, varBuf, sizeof(varBuf));
		var = varBuf;
	}

	/* Write output */
	FILE* fout = fopen(dst, "w");
	if (!fout)
	{
		free(data);
		error("Could not open destination file");
	}

	fprintf(fout, "/* Generated by bin2c from: %s */\n\n", src);
	fprintf(fout, "static const unsigned char %s[%ld] =\n{\n", var, size);

	for (long j = 0; j < size; ++j)
	{
		if (j % 16 == 0)
			fprintf(fout, "\t");

		fprintf(fout, "0x%02x", data[j]);

		if (j < size - 1)
			fprintf(fout, ",");

		if (j % 16 == 15 || j == size - 1)
			fprintf(fout, "\n");
	}

	fprintf(fout, "};\n\n");
	fprintf(fout, "static const unsigned int %s_size = %ld;\n", var, size);

	fclose(fout);
	free(data);

	return 0;
}
